[profile.default]
src = "src"
out = "out"
libs = ["lib"]
optimizer = true
optimizer_runs = 200
via_ir = true
remappings = [
    "@openzeppelin/=lib/openzeppelin-contracts/",
    "forge-std/=lib/forge-std/src/"
]

# See more config options https://github.com/foundry-rs/foundry/tree/master/crates/config

[rpc_endpoints]
worldchain = "https://worldchain-mainnet.g.alchemy.com/public"
worldchain_sepolia = "https://worldchain-sepolia.g.alchemy.com/public"

# [etherscan]
# worldchain = { key = "${ETHERSCAN_API_KEY}", url = "https://worldchain.blockscout.com/api/" }
# worldchain_sepolia = { key = "${ETHERSCAN_API_KEY}", url = "https://worldchain-sepolia.explorer.alchemy.com/api/" }
